### ISSUE TITLE
Installer is broken:

### ISSUE THREAD

**Issue by TylerTheHumanCompiler** [mushware/adanaxis-core-app#1]
`./configure `gives me a file not found error.
`perl autogen autogen.pl` gives me so many errors I can barely count them.
How do I install from source on Arch Linux? (the AUR package is also broken unfortunately)

**Comment by mushware** [comment]
Hi, yep the Linux build hadn't been touched since the repos were moved to Github, which moved lots of files about.  I did manage to get it to build on Arch Linux this morning though, and added the recipe to the [Linux README](https://github.com/mushware/adanaxis/blob/master/README.linux.md).  Can't vouch for builds from master or any of the packaging alas.  I'll need to revisit all of this to get it building on Travis so watch this space 😁

**Comment by TylerTheHumanCompiler** [comment]
Hi, thanks a lot for the quick reply, wasn't expecting that.
I managed to get it running following your new advice in the Linux README, but only after executing the following command after `sudo make install`:
`sudo cp /home/user/Sources/adanaxis/mushruby/mushruby/* /usr/local/share/adanaxis/ruby/`

The game then starts, but crashes immediately after pressing any key, leaving me with this error:
```
Exception: NameError: uninitialized constant MushKeys::KMOD_SHIFT
	from /usr/local/share/adanaxis/ruby/AdanaxisGame.rb:275:in `mKeypress'

```

**Comment by mushware** [comment]
Ah yep looks like the adanaxis-mushruby repo needs taking back to the IMPORTED_FROM_CVS tag too.  Didn't think I'd changed it but, turns out, I have!  Recipe updated - you might need to remove the files you copied to make sure the installed files get picked up.

**Comment by TylerTheHumanCompiler** [comment]
Works flawlessly! Also great and creative game! Thanks a lot for the help!

**Comment by mushware** [comment]
Glad to hear it worked out.  Do let me know if there are any other problems.
